[package]
name = "tuitable_derive"
version = "0.0.1"
edition = "2021"
authors = [ "zhuli <wanlisnx@gmail.com>" ]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.31"
syn = "2.0.27"
tuitable = { path = "../tuitable" }
